apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    annotations:
      - time: timeString
    spec:
      containers:
        - name: eureka-server
          image: registry.cn-shanghai.aliyuncs.com/nocoolming/eureka-server
          ports:
            - containerPort: 8763
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8763
      targetPort: 8763
